config/routes.rb
Rails.application.routes.draw do
  resources :imagens
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/imagen.rb
class Imagen < ApplicationRecord
    mount_uploader :url, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/imagens_controller.rb
class ImagensController < ApplicationController
  before_action :set_imagen, only: [:show, :edit, :update, :destroy]

  # GET /imagens
  # GET /imagens.json
  def index
    @imagens = Imagen.all
  end

  # GET /imagens/1
  # GET /imagens/1.json
  def show
  end

  # GET /imagens/new
  def new
    @imagen = Imagen.new
  end

  # GET /imagens/1/edit
  def edit
  end

  # POST /imagens
  # POST /imagens.json
  def create
    @imagen = Imagen.new(imagen_params)

    respond_to do |format|
      if @imagen.save
        format.html { redirect_to @imagen, notice: 'Imagen was successfully created.' }
        format.json { render :show, status: :created, location: @imagen }
      else
        format.html { render :new }
        format.json { render json: @imagen.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /imagens/1
  # PATCH/PUT /imagens/1.json
  def update
    respond_to do |format|
      if @imagen.update(imagen_params)
        format.html { redirect_to @imagen, notice: 'Imagen was successfully updated.' }
        format.json { render :show, status: :ok, location: @imagen }
      else
        format.html { render :edit }
        format.json { render json: @imagen.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /imagens/1
  # DELETE /imagens/1.json
  def destroy
    @imagen.destroy
    respond_to do |format|
      format.html { redirect_to imagens_url, notice: 'Imagen was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_imagen
      @imagen = Imagen.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def imagen_params
      params.require(:imagen).permit(:url, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/imagens_helper.rb
module ImagensHelper
end

app/views/imagens/_form.html.erb
<%= form_with(model: imagen, local: true) do |form| %>
  <% if imagen.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(imagen.errors.count, "error") %> prohibited this imagen from being saved:</h2>

      <ul>
      <% imagen.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :url %>
    <%= form.file_field :url %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/imagens/edit.html.erb
<h1>Editing Imagen</h1>

<%= render 'form', imagen: @imagen %>

<%= link_to 'Show', @imagen %> |
<%= link_to 'Back', imagens_path %>

app/views/imagens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Imagens</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @imagens.each do |imagen| %>
      <tr>
        <td><img src="<%= imagen.url.thumb %>" alt=""></td>
        <td><%= imagen.name %></td>
        <td><%= link_to 'Show', imagen %></td>
        <td><%= link_to 'Edit', edit_imagen_path(imagen) %></td>
        <td><%= link_to 'Destroy', imagen, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Imagen', new_imagen_path %>

app/views/imagens/new.html.erb
<h1>New Imagen</h1>

<%= render 'form', imagen: @imagen %>

<%= link_to 'Back', imagens_path %>

app/views/imagens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @imagen.url %>
</p>

<p>
  <strong>Name:</strong>
  <%= @imagen.name %>
</p>

<%= link_to 'Edit', edit_imagen_path(@imagen) %> |
<%= link_to 'Back', imagens_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Carrierwave</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>